### ISSUE TITLE
Processess spawned with 'cmd' not getting terminated when your Ctrl-C

### ISSUE THREAD

**Issue by dbp** [ndmitchell/shake#169]
So I have a phony task that starts a process. I expect that if I Ctrl-C, that the signal will be sent to the process, and then shake will continue / terminate (and this is how make works) . But, instead shake terminates (with 'user interrupt'), and the process is still running in the background.

I looked at the various options to run commands with, but didn't see anything obvious. Is the current behavior expected? It seems wrong...

**Comment by ndmitchell** [comment]
See also https://github.com/snowleopard/hadrian/issues/696#issuecomment-459562639 which describes issues around this problem

**Comment by AndreasPK** [comment]
So I tried this using the following code:

```
import Development.Shake
import Development.Shake.Command
import Development.Shake.FilePath
import Development.Shake.Util
import Control.Concurrent
import System.Process

main :: IO ()
main = shakeArgs shakeOptions{shakeFiles="_build"} $ do
    want ["_build/run" <.> exe]



    "_build/run" <.> exe %> \out -> do
        -- cmd_ "Sleep.exe" "" :: Action ()
        liftIO $ system "Sleep.exe"
        liftIO $ threadDelay $ 1000*1000*100

```

And at least for me under mintty the behaviour of cmd, system and process was the same.

**Comment by ndmitchell** [comment]
@AndreasPK and what was that behaviour? Did it work and clean up properly?

**Comment by ndmitchell** [comment]
FWIW I've pushed a lot of patches to this part of the code since the issue was first raised 5 years ago.

**Comment by AndreasPK** [comment]
> @AndreasPK and what was that behaviour? Did it work and clean up properly?

No, it fails to terminate the subprocess and stays active in the background (when run in in the msys shell).

**Comment by hasufell** [comment]
This is still a problem. We have a jenkins that runs shake, which runs docker. If we cancel a job, docker will keep running, because SIGTERM is not propagated.

**Comment by ndmitchell** [comment]
@hasufell - is this pure Linux, or involving msys/mingw or similar?

**Comment by hasufell** [comment]
@ndmitchell linux

**Comment by ndmitchell** [comment]
I note that Docker seems to behave funny in #731 too, CC @symbiont-arnaud-bailly. I've no real idea what is happening here (and completely out of my depth). Maybe the way Docker and System.Process interact is different to normal?

**Comment by hasufell** [comment]
I don't think this has anything to do with docker. Sending SIGTERM to our docker containers manually works fine. We are not using `actionFinally`. If you look at the behavior of `make`, then it sends a SIGTERM to the subprocesses it has spawned. Shake doesn't.

```sh
#!/bin/sh

trap 'echo kill && kill -KILL $child 2>/dev/null' TERM ERR
sleep 500000 &
child=$!
wait $child
```

```make
all:
	./run.sh
```

```hs
#!/usr/bin/env -S cabal new-run
{- cabal:
build-depends: base
            , shake
-}

module Main (main) where

import Development.Shake
import Development.Shake.Classes
import Development.Shake.Command
import Development.Shake.FilePath
import Development.Shake.Rule
import Prelude hiding ((*>))



main :: IO ()
main = do
  shakeArgs shakeOptions { shakeFiles = "_build/"
                         , shakeVerbosity = Loud
                         , shakeThreads = 0
                         , shakeVersion = "4"} $ do

    phony "foo" $ do
      cmd_ "./run.sh"
      pure ()
```

sending SIGTERM to the shake process will not propagate to the script.

**Comment by ndmitchell** [comment]
The `actionFinally` ticket is probably not anything to do with `actionFinally`, but it has Docker as the example command that fails to terminate, making it likely to be the same as your example.

In Shake, when an exception happens, I call [`interruptProcessGroupOf`](https://hackage.haskell.org/package/process-1.6.7.0/docs/System-Process.html#v:interruptProcessGroupOf) which is documented as sending `SIGINT`. Then three seconds after that returns I call [`terminateProcess`](https://hackage.haskell.org/package/process-1.6.7.0/docs/System-Process.html#v:terminateProcess) which sends `SIGKILL`. Is that sufficient to kill Docker? Does the `SIGINT` mess things up? Does the function [`abort`](https://github.com/ndmitchell/shake/blob/master/src/General/Process.hs#L139) in Shake get called?

(I'm on Windows not Linux, so happy to take any advice on the right thing to do here.)

**Comment by hasufell** [comment]
> Then three seconds after that returns I call [`terminateProcess`](https://hackage.haskell.org/package/process-1.6.7.0/docs/System-Process.html#v:terminateProcess) which sends `SIGKILL`.

Afais it sends `SIGTERM`.

> Is that sufficient to kill Docker?

Yes, as described in the minimal example, this has nothing to do with docker.

> Does the SIGINT mess things up?

`SIGINT` propagates properly when I press ctrl-c and `abort` gets called.

> Does the function abort in Shake get called?

When you send `SIGTERM` to the **shake process**: no.

**Comment by hasufell** [comment]
Afais, the problem is

https://github.com/ndmitchell/shake/blob/c3f08f906f41ec62e813a0898897f7f58d804e17/src/General/Process.hs#L159-L160

https://github.com/ndmitchell/shake/blob/c3f08f906f41ec62e813a0898897f7f58d804e17/src/General/Process.hs#L108-L116


This is not signal handling code at all. This is just catching asynchronous exceptions. `SIGINT` seems to be one, but `SIGTERM` is not.

**Comment by ndmitchell** [comment]
Should I be installing a signal handler that turns SIGTERM into an exception so everything terminates properly? Should _all_ Haskell processes be doing that?

**Comment by hasufell** [comment]
To me it seems async exceptions are messy. Taken from the gnu manual

> Macro: int SIGTERM
The SIGTERM signal is a generic signal used to cause program termination. Unlike SIGKILL, this signal can be blocked, handled, and ignored. It is the normal way to politely ask a program to terminate.
> 
> The shell command kill generates SIGTERM by default.

So, in my opinion, a program that receives SIGTERM and decides it is OK to terminate, should also clean up after itself. That is... send SIGTERM to sub-processes, wait for a grace period, then send SIGKILL. 

I don't think the question can be answered for every process, though.

**Comment by ndmitchell** [comment]
It seems that if your advice is right (and I have no reason to suspect its not!), then it should be the default of every Haskell program to turn SIGTERM into an async exception and let that take out the program. Why isn't that done for everyone by default? I don't think anything makes Shake special in this regard. Just trying to understand the context before doing something different for Shake.

**Comment by hasufell** [comment]
I think the problem here is that as the gnu manual says: SIGTERM may be ignored!

If we turn it into an async exception and people don't catch it... oops. So in my opinion it's really up to the program implementor on whether and how to define it. For everything else, there is SIGKILL.

**Comment by symbiont-arnaud-bailly** [comment]
FWIW, I have written some tool last year that spawned processes and managed them, and I baked in signal handling (SIGINT and SIGTERM essentially) because that's the expected behaviour in Unix-land: When a user hits Ctrl-C it expects the foreground process to terminate and cleanup properly.

**Comment by hasufell** [comment]
> When a user hits Ctrl-C it expects the foreground process to terminate and cleanup properly.

That's true. When you run the following C program without explicit signal handling and hit Ctrl-C, then it terminates the child processes as well:

```c
#include <stdio.h>
#include <unistd.h>

int main() {
  printf("hi 2 u\n");
  int mypid = fork();

  if (0 == mypid) {
    sleep(500000);
  } else {
    while (1) {
      printf("lol parent\n");
      sleep(2);
    }
  }

  return (0);
}
```

However, if you send SIGTERM to the parent, the child will keep running. This is why I think the default behavior for haskell programs should be left unchanged, but SIGTERM be implemented specifically for shake to match make behavior.

**Comment by symbiont-arnaud-bailly** [comment]
> When you run the following C program without explicit signal handling and hit Ctrl-C, then it terminates the child processes as well:
That's true but it's because the _shell itself_ handles SIGINT properly, propagating the signal to the foreground _process group_. If you properly detach the subprocess, creating its own subgroup, then it won't receive SIGINT. 
If you manually send SIGTERM using a process's PID, then the signal is not by default propagated to children which explains why the child process does not terminate in this case.

IMHO, shake should handle SIGINT and SIGTERM in such a way that all its subprocesses receive the signal, using standard POSIX signal handling which, obviously, only make sense on an Unix system. And it should probably use the Windows specific mechanism to provide this behaviour on Win32 platform.

**Comment by hasufell** [comment]
> That's true but it's because the _shell itself_ handles SIGINT properly

Nice catch. Now I'm starting to wonder what happens if that shell behavior might not in fact be problematic if the process has its own implementation of reacting to SIGINT?

**Comment by symbiont-arnaud-bailly** [comment]
If a subprocess of a shell handles SIGINT, I guess it can do whatever it please, including refusing to quit :) That's why there is SIGKILL and SIGSTOP which cannot have handlers attached.

**Comment by hasufell** [comment]
I meant that the shell will apparently send SIGINT to the sub processes without letting the parent process decide what to do?

**Comment by symbiont-arnaud-bailly** [comment]
If they are part of the same process group, which is the case by default, yes. But then the parent could handle SIGCHLD :)

**Comment by symbiont-arnaud-bailly** [comment]
The semantics of signals is fascinating, and the number of potential pitfalls staggering!

**Comment by hasufell** [comment]
@ndmitchell do you have a clearer picture about the problem now? Do you need further information?

**Comment by ndmitchell** [comment]
Thanks for all your discussion on this topic, but my current state is I'm totally confused. There was a long discussion about signals at #748 and StackOverflow info at https://stackoverflow.com/questions/61856063/spawning-a-process-with-create-group-true-set-pgid-hangs-when-starting-docke/61881005#61881005. It would be great to get a 5-year-old style answer to:

* What behaviour should change?
* What should Shake do to make that change?
* Are there any downsides to that change?
* Why should Shake do this and not _all_ Haskell programs?

**Comment by mpickering** [comment]
> I don't think this has anything to do with docker. Sending SIGTERM to our docker containers manually works fine. We are not using `actionFinally`. If you look at the behavior of `make`, then it sends a SIGTERM to the subprocesses it has spawned. Shake doesn't.
> 
> ```shell
> #!/bin/sh
> 
> trap 'echo kill && kill -KILL $child 2>/dev/null' TERM
> sleep 500000 &
> child=$!
> wait $child
> ```
> 
> ```makefile
> all:
> 	./run.sh
> ```
> 
> ```haskell
> #!/usr/bin/env -S cabal new-run
> {- cabal:
> build-depends: base
>             , shake
> -}
> 
> module Main (main) where
> 
> import Development.Shake
> import Development.Shake.Classes
> import Development.Shake.Command
> import Development.Shake.FilePath
> import Development.Shake.Rule
> import Prelude hiding ((*>))
> 
> 
> 
> main :: IO ()
> main = do
>   shakeArgs shakeOptions { shakeFiles = "_build/"
>                          , shakeVerbosity = Loud
>                          , shakeThreads = 0
>                          , shakeVersion = "4"} $ do
> 
>     phony "foo" $ do
>       cmd_ "./run.sh"
>       pure ()
> ```
> 
> sending SIGTERM to the shake process will not propagate to the script.

1. This reply is about `SIGTERM`, not `SIGINT`. Ctrl-C sends `SIGINT` to the process and so `SIGTERM` is irrelevant. For `SIGTERM` handling you need to install a custom handler as there's no special handling in the RTS as there is for `SIGINT`. 

2. If you modify your program to catch `SIGINT` then shake cleans up correctly. 

So I'm not sure there is even a problem with `SIGINT`.
